from pathlib import Path

MODEL_PATH = None
LABELS_PATH = Path(__file__).resolve().parent / "domain" / "imagenet_labels.json"
TOP_K = 10
REQUEST_TIMEOUT = 15.0
MAX_IMAGE_SIZE = 800
MODERATION_ENABLED = True
MODERATION_THRESHOLD = 0.15
PROHIBITED_INDICES = {414, 764, 765}
NSFW_ENABLED = True
NSFW_THRESHOLD = 0.35
NSFW_EXPLICIT_CLASSES = frozenset({
    "FEMALE_GENITALIA_EXPOSED",
    "FEMALE_BREAST_EXPOSED",
    "MALE_GENITALIA_EXPOSED",
    "MALE_BREAST_EXPOSED",
    "BUTTOCKS_EXPOSED",
    "ANUS_EXPOSED",
})
MAX_VIDEO_FRAMES = 30
VIDEO_FRAME_INTERVAL_SEC = 2.0
MAX_VIDEO_SIZE_BYTES = 100 * 1024 * 1024
