import os

from config import LOCAL_MODELS_ROOT

RECOMMENDATION_MODEL_DIR = LOCAL_MODELS_ROOT / "recommendation" / "models"
FEED_RANKER_MODEL = RECOMMENDATION_MODEL_DIR / "feed_ranker.pt"

DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://chat:chat123@localhost:5433/chat")
REDIS_URL = "redis://localhost:6379"
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")
CELERY_BROKER_URL = "redis://localhost:6379/0"
CASSANDRA_CONTACT_POINTS = ["localhost"]
CASSANDRA_KEYSPACE = "chat"
CASSANDRA_LOCAL_DC = "datacenter1"

VECTOR_BACKEND = "redis"
FAISS_DIM = 64
FAISS_INDEX_PATH = None
FAISS_IDS_PATH = None

SUGGESTION_REDIS_KEY_PREFIX = "recommendation:user:"
SUGGESTION_TTL_SECONDS = 3600
SUGGESTION_MAX_PER_USER = 50
FRIEND_OF_FRIEND_FOLLOWING_LIMIT = 500
